In [4]:
#### Detectron2.0 install
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/c7/mj5j7pjj74s0m10__w_qqlbc0000gn/T/pip-req-build-lrpaagx9
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /private/var/folders/c7/mj5j7pjj74s0m10__w_qqlbc0000gn/T/pip-req-build-lrpaagx9
  Resolved https://github.com/facebookresearch/detectron2.git to commit 115dc5c8bfd434f9a3f5070147d863d9419cfb7e
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.8/153.8 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.1/549.1 kB 19.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━

  Created wheel for detectron2: filename=detectron2-0.6-cp310-cp310-macosx_11_0_arm64.whl size=850395 sha256=916933475e98852f8091890f9985d419ffd2f794a7ea79eefe9a70eb7b5c9a62
  Stored in directory: /private/var/folders/c7/mj5j7pjj74s0m10__w_qqlbc0000gn/T/pip-ephem-wheel-cache-v31hgw5n/wheels/47/e5/15/94c80df2ba85500c5d76599cc307c0a7079d0e221bb6fc4375
  Created wheel for fvcore: filename=fvcore-0.1.5.post20221122-py3-none-any.whl size=61458 sha256=d65f313d661ffdcb38cc5667fc70e87196974e2c706bac9f8317cee83fba423b
  Stored in directory: /Users/pritiranjansahoo/Library/Caches/pip/wheels/ab/6e/17/e1b7e37b8381ddab1302572d133035f8962f7bbd1642c26670
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144554 sha256=1c71ff0e2f66a93ab7534b3eea978a5cab76e2960ba9a4ee5db0c74818acd3bd
  Stored in directory: /Users/pritiranjansahoo/Library/Caches/pip/wheels/48/6a/c2/acb58c7afdf57e4cddf5e1513f5a2d62aa8e98f82a00c76d7c
  Created wheel for pycocotools: fil

In [6]:
#### Libraries
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import cv2
import random
#from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
from detectron2.data.catalog import DatasetCatalog

/Users/pritiranjansahoo/miniforge3/envs/legion3.0/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/pritiranjansahoo/miniforge3/envs/legion3.0/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
  Referenced from: <D9493EF5-8DAB-3A5D-85D5-684F04544B84> /Users/pritiranjansahoo/miniforge3/envs/legion3.0/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <BB02660F-1D5B-3388-B48B-486877D726F6> /Users/pritiranjansahoo/miniforge3/envs/legion3.0/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")


In [93]:
#### trimming images
path = '../documentations and prior code/Team project/files/jpg/all/'
output_path = '../documentations and prior code/Team project/files/jpg/preprocessed_images/'
sys.path.append(path)

import cv2
import numpy as np
from PIL import Image
import imutils
from imutils.perspective import four_point_transform
import argparse
import re

def processImage(img_path,filename, show=0):
    # Read image with opencv
    img = cv2.imread(img_path)
    img, arraytoPrint = croppingImage(img)
    cv2.imwrite(output_path+filename, img)
    if show==1:
        cv2.imshow("image",img)
        cv2.waitKey(0)
    #return img

def croppingImage(img):
    arraytoPrint = []
    orig = img
    image = orig.copy()
    input_width = int(image.shape[1]/2)
    input_height = int(image.shape[0]/2)
    image = cv2.resize(image, (input_width, input_height))
    orig_image = image.copy()
    ratio = orig.shape[1] / float(image.shape[1])

    # convert the image to grayscale, blur it, and apply edge detection
    # to reveal the outline
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 1)

    # Detect white regions
    rectKernel = cv2.getStructuringElement(cv2.MORPH_RECT, (50, 100))
    dilated = cv2.dilate(blurred, rectKernel)
    
    #edge
    edged = cv2.Canny(blurred, 30, 150)

    for i in range(input_height):
        if (i != 0) & (i != input_height-1):
            edged[i,0] = 255
            edged[i,input_width-1] = 255
        if (i == 0) | (i == input_height-1):
            edged[i,] = np.repeat(255, input_width)

    # detect contours in the edge map, sort them by size (in descending
    # order), and grab the largest contours
    cnts = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    cnts = sorted(cnts, key=cv2.contourArea, reverse=True)
    
    # initialize a contour
    imageCnt = None

    # loop over the contours
    for c in cnts:
        peri = cv2.arcLength(c, True)# approximate the contour
        approx = cv2.approxPolyDP(c, 0.05* peri, True)
 
        # Evaluating area of approx
        a_list = []
        b_list = []
        for i in approx:
            a = i[0][0]
            b = i[0][1]
            a_list.append(a) 
            b_list.append(b)
        area = (max(a_list) - min(a_list)) * (max(b_list) - min(b_list))
        if (len(approx) == 4) & (area < 0.99*(input_height-1)*(input_width-1)):
            if area >= 10000: 
                imageCnt = approx
                break
            if area < 10000:
                imageCnt = np.array([[[input_width-1, 0]], [[0, 0]], [[0, input_height-1]],
                                     [[input_width-1, input_height-1]]], dtype = 'int32')

    output = image.copy()
    cv2.drawContours(output, [imageCnt], -1, (0, 255, 0), 2)
    output = cv2.resize(output, None, fx=0.3,fy=0.3)
    arraytoPrint.append(['Outline/Borders',output])

    cropped = four_point_transform(image, imageCnt.reshape(4, 2))
    # show transformed image
    output = cv2.resize(cropped, None, fx=0.3,fy=0.3)

    arraytoPrint.append(['Cropped',output])
    #1 showimage("cropped", output)
    #  cv2.waitKey(0)
    return cropped, arraytoPrint

<IPython.core.display.Javascript object>

In [94]:
#### preprocessing

print ('--- Start processing the image ---')
jpg_path = path

"""loading all images"""
def loadImagesFromjpg(directory):
    print("loading invoices from", directory)
    files = os.listdir(directory)
    for file in files:
        if not file.endswith('.jpg'):
            continue
        filename = f'{file}'
        processImage(directory + filename,filename,0 )
    return True

loadImagesFromjpg(jpg_path)

--- Start processing the image ---
loading invoices from ../documentations and prior code/Team project/files/jpg/all/


<IPython.core.display.Javascript object>

Corrupt JPEG data: 7089 extraneous bytes before marker 0xd0


True

In [98]:
import torch

# Define a matrix of tensors
target_matrix = torch.randn(3, 5, 2)
print(target_matrix)
# Use torch.where to compute the element-wise maximum
results = [torch.where(t)[0].tolist() for t in target_matrix]

# Print the results
print(results)

tensor([[[ 0.7647,  1.5733],
         [-0.9110, -0.6892],
         [ 0.6521, -1.0874],
         [-0.8866,  0.6378],
         [ 0.2679, -0.9309]],

        [[-0.3121, -0.5707],
         [-0.7031,  0.0121],
         [ 0.7592,  0.7969],
         [ 0.2684,  0.2374],
         [-0.2452,  0.6432]],

        [[ 0.0248,  0.0024],
         [-0.8785,  1.5179],
         [-1.5664,  1.0685],
         [-0.2634, -0.2735],
         [ 0.5853, -0.4334]]])
[[0, 0, 1, 1, 2, 2, 3, 3, 4, 4], [0, 0, 1, 1, 2, 2, 3, 3, 4, 4], [0, 0, 1, 1, 2, 2, 3, 3, 4, 4]]


In [101]:
for t in target_matrix:
    print(torch.where(t))

(tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]), tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))
(tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]), tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))
(tensor([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]), tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))
